tests:
  - tests/*

docs:
  - README.md

legal:
  - LICENSE

package:
  - requirements.txt
  - MANIFEST.in
  - setup.py

rules:
  - CODE_OF_CONDUCT.md

gpo:
  - vistos/src/gpo/*

workflows:
  - .github/*

core:
  - vistos/src/duo.py

update:
  - vistos/VERSION