name: integration-tests

on:
  workflow_run:
    workflows: ['test-build']
    branches:
      - test
    types:
      - completed

jobs:
  run-integration-tests:
    name: Run integration test cases
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Step up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Wait 10 mins for latest version to become available on TestPyPI
        run: |
          sleep 10m
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-decouple
          pip install -r requirements.txt
      - name: Test pip install
        run: |
          pip install -i https://test.pypi.org/simple/ vistos
      - name: Run test cases
        env:
          GOVINFO_API_KEY: ${{ secrets.GOVINFO_API_KEY }}
        run: |
          python tests/test_integration.py
