name: run integration test cases

on:
  workflow_dispatch:
    inputs:
      govinfo_key:
        description: 'GovInfo API Key'
        default: ${{ secrets.GOVINFO_API_KEY }}
        required: true

jobs:
  run-integration-tests:
    name: Run test cases
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Step up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -i https://test.pypi.org/simple/ quinque
    - name: Run test cases
      env:
        GOVINFO_API_KEY: ${{ github.event.inputs.govinfo_key }}
      run: |
        python tests/test_integration.py