name: run test cases

on:
  push:
    branches:
      - test
      - develop
      - master

jobs:
  run-test-cases:
    name: Run test cases
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Step up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run test cases
      run: |
        python tests/test_cases.py