name: Run test cases
on:
  push:
    branches:
      - develop

jobs:
  run-test-cases:
    name: Run test cases
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Step up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install test dependencies
      run: |
        pip install -r requirements.txt
        pip install -i https://test.pypi.org/simple/ quinque
    - name: Run test cases
      run: |
        python tests/test_func.py
