name: Publish test branch to TestPyPI

on:
  push:
    paths:
      - vistos/VERSION
    branches:
      - test

jobs:
  run-unit-tests:
    name: Run unit test cases
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Step up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run test cases
        run: |
          python tests/test_unit.py

  build-and-publish:
    name: Build test branch and publish to Test PyPI
    runs-on: ubuntu-18.04
    needs: run-unit-tests

    steps:
      - uses: actions/checkout@master
      - name: Step up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        run: |
          twine upload --repository testpypi dist/*
